---
- set_fact:
    collectionHash: '{{ hostvars[item][reference] }}'
  with_items:
    - "{{ groups['primaryAppliance'] }}"
  no_log: true

- name: Query and store existing service_catalogs 
  uri:
    url: https://"{{ groups['primaryAppliance'][0] | default('https://localhost') }}"/api/service_catalogs?expand=resources&attributes=id,name
    method: GET
    headers:
      X-Auth-Token: "{{ collectionHash['loginCookie'] }}"
    validate_certs: no
    status_code: 200
  register: ___miq_register_serviceCatalogs
  no_log: true

- name: create service catalog map
  set_fact:
    ___miq_data_serviceCatalogMap: '{{ ___miq_data_serviceCatalogMap | default({}) | combine( { item.name: item.id } ) }}'
  with_items:
    - "{{ ___miq_register_serviceCatalogs.json.resources }}"
  no_log: true

- set_fact:
    tmpHash: "{{ tmpHash | default({}) | combine( { item.key: item.value } ) }}"
  with_dict:
    - "{{ collectionHash }}"
    - { 'serviceCatalogMap': '{{ data }}' }
  vars:
    data: "{{ ___miq_data_serviceCatalogMap }}"
  no_log: true

- set_fact:
    "{{ reference }}": '{{ tmpHash }}'
  delegate_to: "{{ item }}"
  delegate_facts: true
  with_items: "{{ groups['primaryAppliance'] }}"
  no_log: true

