---
- set_fact:
    collectionHash: '{{ hostvars[item][reference] }}'
  with_items:
    - "{{ groups['primaryAppliance'] }}"
  no_log: true

- name: Query and store existing providers 
  uri:
    url: https://"{{ groups['primaryAppliance'][0] | default('https://localhost') }}"/api/providers?expand=resources&attributes=id,name,type
    method: GET
    headers:
      X-Auth-Token: "{{ collectionHash['loginCookie'] }}"
    validate_certs: no
    status_code: 200
  register: ___miq_register_Providers
  no_log: true

- name: create provider map
  set_fact:
    ___miq_data_providerMap: "{{ ___miq_data_providerMap | default({}) | combine( { item.name: item.id } ) }}"
  with_items:
    - "{{ ___miq_register_Providers | json_query(jq) }}"
  vars:
    jq: "json.resources[?type == 'ManageIQ::Providers::AnsibleTower::AutomationManager'].{ name: name, id: id }"
  no_log: true

- set_fact:
    tmpHash: "{{ tmpHash | default({}) | combine( { item.key: item.value } ) }}"
  with_dict:
    - "{{ collectionHash }}"
    - { 'providerMap': '{{ data }}' }
  vars:
    data: "{{ ___miq_data_providerMap }}"
  no_log: true

- set_fact:
    "{{ reference }}": '{{ tmpHash }}'
  delegate_to: "{{ item }}"
  delegate_facts: true
  with_items: "{{ groups['primaryAppliance'] }}"
  no_log: true
