---
- set_fact:
    collectionHash: '{{ hostvars[item][reference] }}'
  with_items:
    - "{{ groups['primaryAppliance'] }}"
  no_log: true

- name: Query and store existing service_templates 
  uri:
    url: https://"{{ groups['primaryAppliance'][0] | default('https://localhost') }}"/api/service_dialogs?expand=resources&attributes=id,label
    method: GET
    headers:
      X-Auth-Token: "{{ collectionHash['loginCookie'] }}"
    validate_certs: no
    status_code: 200
  register: ___miq_register_serviceDialogs
  no_log: true

- name: create service dialog map
  set_fact:
    ___miq_data_serviceDialogMap: '{{ ___miq_data_serviceDialogMap | default({}) | combine( { item.label: item.id } ) }}'
  with_items:
    - "{{ ___miq_register_serviceDialogs.json.resources }}"
  no_log: true

- set_fact:
    tmpHash: "{{ tmpHash | default({}) | combine( { item.key: item.value } ) }}"
  with_dict:
    - "{{ collectionHash }}"
    - { 'serviceDialogMap': '{{ data }}' }
  vars:
    data: "{{ ___miq_data_serviceDialogMap }}"
  no_log: true

- set_fact:
    "{{ reference }}": '{{ tmpHash }}'
  delegate_to: "{{ item }}"
  delegate_facts: true
  with_items: "{{ groups['primaryAppliance'] }}"
  no_log: true

